// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byaxzuhwpgefigjwgapt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YXh6dWh3cGdlZmlnandnYXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTg4MTIsImV4cCI6MjA2MTU5NDgxMn0.Tczk9nVHxvM7yjC9ZdjaaqRlybhsO51ZyWNUdN_uCTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);